homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Environmental
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 172.19.0.0/16
      allow_bypass_login: true
    - type: homeassistant

http:

frontend:

config:

view_event:

sun:

weather: !include_dir_list weather
sensor: !include_dir_list sensors
